name: Default pipeline

on:
  push:
    branches:
      - master

jobs: 
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install
        run: npm install
      - name: npm eslint
        run: npm run eslint