name: Default pipeline

on:
  push:
    branches:
      - master

jobs: 
  simple_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install
        run: npm install
      - name: npm eslint
        run: npm run eslint
      - name: npm test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run start-prod
          wait-on: 'http://localhost:5000'
          wait-on-timeout: 120